# Generated by Django 5.2.17 on 2026-08-10 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Ready', 'Ready')], default='Pending', max_length=50)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='references/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolioitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Inquiries',
        ),
    ]
