# Generated by Django 5.2.17 on 2026-08-30 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_delete_inquiries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='reference_image',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(default='shariq7@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='message',
            field=models.TextField(default='ajay stitching'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name',
            field=models.CharField(default='Ajay', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(default='stitching', max_length=200),
            preserve_default=False,
        ),
    ]
