# Generated by Django 5.2.17 on 2026-08-30 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_remove_inquiry_customer_and_more'),
        ('portfolio', '0002_remove_portfolioitem_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolioitem'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiry_references/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
