# Generated by Django 5.2.17 on 2026-08-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_inquiry_customer_inquiry_internal_notes_inquiry_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cutting', 'Cutting')], default='Pending', max_length=20),
        ),
    ]
