# Generated by Django 5.2.17 on 2026-08-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_inquiry_phone_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='chest',
            field=models.CharField(blank=True, help_text='e.g., 40 inches', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inseam',
            field=models.CharField(blank=True, help_text='e.g., 32 inches', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='item_category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Suit', 'Suit')], default='Shirt', max_length=20),
        ),
    ]
