# Generated by Django 5.2.17 on 2026-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_alter_inquiry_status_inquiryreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='item_category',
            field=models.CharField(blank=True, choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Suit', 'Suit')], max_length=20, null=True),
        ),
    ]
