# Generated by Django 5.2.17 on 2026-09-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_serviceprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePrice',
        ),
    ]
