# Generated by Django 5.2.17 on 2026-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0010_delete_serviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryreply',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiry_references/'),
        ),
    ]
