# Generated by Django 5.2.17 on 2026-09-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0011_inquiryreply_reference_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryreply',
            name='reference_image',
        ),
    ]
