# Generated by Django 5.2.17 on 2026-08-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_chest_userprofile_hips_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='hips',
            new_name='shoulder_width',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='inseam',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
