# Generated by Django 5.2.17 on 2026-08-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Shirts', 'Shirts'), ('Pants', 'Pants'), ('Suits', 'Suits'), ('Jackets', 'Jackets'), ('Coats', 'Coats'), ('Dresses', 'Dresses'), ('Skirts', 'Skirts'), ('Blouses', 'Blouses'), ('Sweaters', 'Sweaters'), ('Cardigans', 'Cardigans'), ('Vests', 'Vests'), ('Shorts', 'Shorts'), ('Activewear', 'Activewear'), ('Loungewear', 'Loungewear'), ('Sleepwear', 'Sleepwear'), ('Swimwear', 'Swimwear')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Business', 'Business'), ('Evening', 'Evening'), ('Party', 'Party'), ('Wedding', 'Wedding'), ('Cocktail', 'Cocktail'), ('Prom', 'Prom'), ('Beachwear', 'Beachwear'), ('Resortwear', 'Resortwear'), ('Athleisure', 'Athleisure'), ('Streetwear', 'Streetwear'), ('Vintage', 'Vintage'), ('Bohemian', 'Bohemian'), ('Preppy', 'Preppy'), ('Gothic', 'Gothic')], max_length=50, null=True)),
                ('price', models.CharField(blank=True, choices=[('Under $50', 'Under $50'), ('$50 - $100', '$50 - $100'), ('$100 - $200', '$100 - $200'), ('$200 - $500', '$200 - $500'), ('$500 - $1000', '$500 - $1000'), ('Over $1000', 'Over $1000')], max_length=50, null=True)),
                ('image_type', models.CharField(blank=True, choices=[('Front View', 'Front View'), ('Back View', 'Back View'), ('Side View', 'Side View'), ('Close-up', 'Close-up'), ('Detail Shot', 'Detail Shot'), ('Full Outfit', 'Full Outfit'), ('Lifestyle', 'Lifestyle'), ('Runway', 'Runway'), ('Editorial', 'Editorial'), ('Street Style', 'Street Style')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
            ],
        ),
    ]
