# Generated by Django 5.2.17 on 2026-08-13 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image_type',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 13, 19, 20, 52, 709796, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(default='untitled', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
