# Generated by Django 5.2.17 on 2026-09-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_serviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='base_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
