# Generated by Django 5.2.17 on 2026-09-28 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolioitem_base_price_portfolioitem_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_starting_price', models.DecimalField(decimal_places=2, default=1299.0, max_digits=8)),
                ('icon_emoji', models.CharField(default='👔', help_text='Emoji icon for studio UI', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1299.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(default='', upload_to='portfolio_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='portfolio.category'),
        ),
    ]
